"""empty message

Revision ID: 26dca939fcbd
Revises: 
Create Date: 2019-07-24 12:59:09.833366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dca939fcbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=256), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db')
    # ### end Alembic commands ###
