"""empty message

Revision ID: 6e90fbf90bed
Revises: 
Create Date: 2019-07-22 23:15:11.861217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e90fbf90bed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spam_db',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=256), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spam_db')
    # ### end Alembic commands ###
