"""empty message

Revision ID: 85bfedf418e3
Revises: 26dca939fcbd
Create Date: 2019-07-24 13:12:16.619394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85bfedf418e3'
down_revision = '26dca939fcbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"db_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('document', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('createDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='db_pkey')
    )
    # ### end Alembic commands ###
