"""empty message

Revision ID: ffbd3d3da6b0
Revises: 6e90fbf90bed
Create Date: 2019-07-23 00:13:21.996577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffbd3d3da6b0'
down_revision = '6e90fbf90bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=256), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('spam_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spam_db',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"spam_db_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('document', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('createDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='spam_db_pkey')
    )
    op.drop_table('db')
    # ### end Alembic commands ###
